### ISSUE TITLE
Request for another format of PCB design file

### ISSUE THREAD

**Issue by ohchiko** [SethSenpai/Tanuki#1]
Hey, I think it would be good if you can provide another format of the pcb design. The problem currently I have is there's no pcb printing service in my country that can use the gerber or the kicad. They use pdf, protel, altium, and eagle (but mostly use pdf).

And I know I can order using the gerber by the jlcpcb, but the shipping is too expensive (using dhl is 3 times of the board price). So I'd rather use the pcb printing service in my country instead.

I hope you can provide at least one of them.

Thanks!

**Comment by SethSenpai** [comment]
I added a pdf version of the pcb files in the latest commit #e18efab. Got to admit never worked with a company that doesn't accept gerber but I guess its fair with it being a 20 year old standard almost. 😄
