### ISSUE TITLE
OSS License

### ISSUE THREAD

**Issue by ymotongpoo** [SethSenpai/Tanuki#3]
Thank you for open sourcing the data of the awesome keyboard. Could you add OSS license to the repo just in case?

**Comment by SethSenpai** [comment]
At the time I decided to not give the repository a lisence because there wasn't a license avaiable that fit what I wanted to do with the project. However times have changed and perhaps it is time to slap a lisence on this. Do you have any suggestions?

**Comment by ymotongpoo** [comment]
Thank you for the quick response! Say MIT, GPL, CC BY-SA sounds awesome!

**Comment by SethSenpai** [comment]
MIT seemed to cover most of the things I wanted. I updated the repo with the license file.

**Comment by ymotongpoo** [comment]
Awesome! I appreciate it!
