### ISSUE TITLE
What can I do if I use the 3d printing case?

### ISSUE THREAD

**Issue by Mark-Miao** [SethSenpai/Tanuki#5]
There is a problem that we don't have any mount holes on the front of the model
![屏幕截图 2024-01-13 164446](https://github.com/SethSenpai/Tanuki/assets/62823744/4d5439b7-f06b-4351-b380-a4f8e08575ce)
So how can I mount the back?

**Comment by SethSenpai** [comment]
Hey there, The idea is to use the holes on the back to mount a baseplate to the top of the device. This takes normal M3 bolts and should close up the device fully.

**Comment by Mark-Miao** [comment]
Yep，I noticed that a few minutes later~
